### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by alejandroatacho** [Correia-jpv/github-follow-bot#12]
How do I make the unfollow bot work -w- I am lost now, 

I tried several ways including using -t and my GitHub name and revoking token and regenerating the token and update .env

Can you just type an example of how to use the unfollow bot using the -nf

![image](https://user-images.githubusercontent.com/15048157/189492472-c0bade3e-7bb0-4ede-b7ae-ede6eb1e2db6.png)
`cd follow-bot && python bot_unfollow.py -fo`

![image](https://user-images.githubusercontent.com/15048157/189492522-3f17cb0f-51f6-48d5-83b5-ba8f68724d50.png)
`cd follow-bot && python bot_unfollow.py -nf -smin 50`

**Comment by Correia-jpv** [comment]
Both of your commands are correct and working as intended on the latest version.
Please, check if you have it and also set your `.env` file as in the sample template: https://github.com/Correia-jpv/github-follow-bot/blob/4a7709912bae0c3142b34545a88a93ad92555280/.env.sample

**Comment by alejandroatacho** [comment]
![image](https://user-images.githubusercontent.com/15048157/194721268-5ef7cfcc-16bc-47d4-8bfd-08f34432befb.png)

Tried new personal token and re-upload .env 
double check username but not solution :x

**Comment by alejandroatacho** [comment]
I found the fix thanks Correia

**Comment by Correia-jpv** [comment]
> I found the fix thanks Correia

Good to know! Cheers
