### ISSUE TITLE
[BUG] broken unfollow 

### ISSUE THREAD

**Issue by alejandroatacho** [Correia-jpv/github-follow-bot#3]
None of the unfollowing functions is working.

unless I am the one using it wrong...

**Comment by Correia-jpv** [comment]
Please share the unfollowing commands you've tried that aren't working for you

**Comment by alejandroatacho** [comment]
This is what I used, the following bot works but unfollow didnt work for me :x none of them.

`cd follow-bot && python bot_unfollow.py -nf`


![image](https://user-images.githubusercontent.com/15048157/182442099-cdcbd28b-3874-4623-935a-ccd82d21f2b4.png)

**Comment by david-kariuki** [comment]
I also have the same problem
